apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    # ALB Core Settings
    alb.ingress.kubernetes.io/group.name: shared-ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:339712902352:certificate/07756fed-11f9-46f1-8abc-7642d6554270
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    
    # Health Check Configuration
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy  # For Prometheus and Grafana
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    
    # Target-specific overrides
    alb.ingress.kubernetes.io/conditions.kube-prometheus-stack-prometheus: |
      [{"field":"host-header","hostHeaderConfig":{"values":["prometheus.devopswithdeepak.co.in"]}}]
    alb.ingress.kubernetes.io/conditions.kube-prometheus-stack-grafana: |
      [{"field":"host-header","hostHeaderConfig":{"values":["grafana.devopswithdeepak.co.in"]}}]

spec:
  ingressClassName: alb
  rules:
    - host: prometheus.devopswithdeepak.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
    - host: grafana.devopswithdeepak.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
